login: &login
  adapter: mysql2
  host: localhost
  username: root
  password:

development: &development
  database: refinerycms-demo
  <<: *login

#test: &test
#  database: your_test_database
#  <<: *login

#production: &production
#  adapter: mysql2
#  host: localhost
#  database: your_production_database
#  username: your_production_database_login
#  password: your_production_database_password

